[build]
command = "yarn build --prefix-paths"

[context.deploy-preview]
command = "yarn build"

# Allow browsing the Netlify URL, https://til.ricostacruz.com.
[[redirects]]
  from = "/til/*"
  to = "/:splat"

[[redirects]]
  from = "https://til.ricostacruz.com/*"
  to = "https://ricostacruz.com/til/:splat"

# https://www.netlify.com/blog/2017/02/23/better-living-through-caching/
# https://www.netlify.com/docs/headers-and-basic-auth/#custom-headers
# https://www.netlify.com/docs/headers-and-basic-auth/#structured-configuration
# https://developers.google.com/web/tools/lighthouse/audits/cache-policy
[[headers]]
  for= "/*"
  [headers.values]
   Cache-Control = "max-age=86400"

[[headers]]
  for= "/static/*"
  [headers.values]
   Cache-Control = "max-age=31536000"
